[custom]
;Do not change keywords arbitrarily, otherwise it will cause errors
;acl4SSR Rules

;Ad Removal: Supported
;Automatic Speed Test: Supported
;Microsoft Proxy: Supported
;Apple Proxy: Supported
;Enhanced China IP Segment: Supported
;Enhanced Foreign GFW: Supported

;设置Rule Flags
ruleset=🎯 Direct Connection,https://raw.githubusercontent.com/x-bam/clash_config/refs/heads/main/ruleset/vlandirect.list
ruleset=🚀 Node Selection,https://raw.githubusercontent.com/x-bam/clash_config/refs/heads/main/ruleset/iptoproxy.list
ruleset=🎯 Direct Connection,[]GEOSITE,private
ruleset=🎯 Direct Connection,[]GEOIP,private,no-resolve
ruleset=🎯 Direct Connection,[]GEOSITE,category-games@cn
ruleset=🎯 Direct Connection,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list
ruleset=🎯 Direct Connection,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Game_Download_CDN.list
ruleset=🎯 Direct Connection,[]GEOSITE,category-public-tracker
ruleset=💬 MessagingApps,[]GEOSITE,category-communication
ruleset=💬 MessagingApps,[]GEOIP,telegram,no-resolve
ruleset=📱 SocialMedia,[]GEOSITE,category-social-media-!cn
ruleset=📱 SocialMedia,[]GEOIP,twitter,no-resolve
ruleset=📱 SocialMedia,[]GEOIP,facebook,no-resolve
ruleset=🙋 Reddit,[]GEOSITE,reddit
ruleset=🤖 AI,[]GEOSITE,category-ai-!cn
ruleset=🚀 Node Selection,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=📹 YouTube,[]GEOSITE,youtube
ruleset=🍎 Apple,[]GEOSITE,apple
ruleset=Ⓜ️ Microsoft,[]GEOSITE,microsoft
ruleset=📢 Google FCM,[]GEOSITE,googlefcm
ruleset=🇬 GoogleServices,[]GEOSITE,google
ruleset=🇬 GoogleServices,[]GEOIP,google,no-resolve
ruleset=🎥 Netflix,[]GEOSITE,netflix
ruleset=🎥 Netflix,[]GEOIP,netflix,no-resolve
ruleset=🎥 DisneyPlus,[]GEOSITE,disney
ruleset=🎥 PrimeVideo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.list
ruleset=🇩🇪📺 GermanTV,https://raw.githubusercontent.com/x-bam/clash_config/refs/heads/main/ruleset/GermanTV.list
ruleset=🎻 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🎮 Steam,[]GEOSITE,steam
ruleset=🎮 Gaming Platform,[]GEOSITE,category-games
ruleset=🌏 Domestic Media,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 Foreign Media,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌈 Usenet,https://raw.githubusercontent.com/x-bam/clash_config/refs/heads/main/ruleset/usenet.list
;ruleset=🚀 Node Selection,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 Direct Global Connection,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
;ruleset=🎯 Direct Global Connection,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 Direct Connection,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 Direct Connection,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 Direct Connection,[]GEOSITE,cn
ruleset=🎯 Direct Connection,[]GEOIP,cn,no-resolve
ruleset=🐟 Others,[]FINAL
;设置Rule Flags

;设置分组标志位
custom_proxy_group=🚀 Node Selection`select`[]♻️ Automatic Selection`[]🇭🇰 Hong Kong Node`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇸🇬 Singapore Node`[]🇯🇵 Japan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🚀 Manual Switch`select`.*
custom_proxy_group=♻️ Automatic Selection`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=💬 MessagingApps`select`[]🇭🇰 Hong Kong Node`[]🇯🇵 Japan Node`[]🇸🇬 Singapore Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=📱 SocialMedia`select`[]🇭🇰 Hong Kong Node`[]🇯🇵 Japan Node`[]🇸🇬 Singapore Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🤖 AI`select`[]🇭🇰 Hong Kong Node`[]🇯🇵 Japan Node`[]🇸🇬 Singapore Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🇭🇰 Hong Kong Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇸🇬 Singapore Node`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇯🇵 Japan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🎥 Netflix`select`[]🇺🇲 US Node`[]🎥 Netflix Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇸🇬 Singapore Node`[]🇭🇰 Hong Kong Node`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇯🇵 Japan Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🎥 PrimeVideo`select`[]🇩🇪 German Node`[]🎥 Netflix Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇸🇬 Singapore Node`[]🇭🇰 Hong Kong Node`[]🇨🇳 Taiwan Node`[]🇯🇵 Japan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🎥 DisneyPlus`select`[]🇭🇰 Hong Kong Node`[]🎥 Netflix Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇸🇬 Singapore Node`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇯🇵 Japan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🇩🇪📺 GermanTV`select`[]🇩🇪 German Node
custom_proxy_group=🙋 Reddit`select`[]🇩🇪 German Node`[]🇺🇲 US Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇸🇬 Singapore Node`[]🇭🇰 Hong Kong Node`[]🇨🇳 Taiwan Node`[]🇯🇵 Japan Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🎻 Spotify`select`[]🇭🇰 Hong Kong Node`[]🇯🇵 Japan Node`[]🇸🇬 Singapore Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🌍 Foreign Media`select`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇭🇰 Hong Kong Node`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇸🇬 Singapore Node`[]🇯🇵 Japan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🌏 Domestic Media`select`[]DIRECT`[]🇭🇰 Hong Kong Node`[]🇨🇳 Taiwan Node`[]🇸🇬 Singapore Node`[]🇯🇵 Japan Node`[]🚀 Manual Switch
custom_proxy_group=📢 Google FCM`select`[]🇭🇰 Hong Kong Node`[]🇯🇵 Japan Node`[]🇸🇬 Singapore Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🇬 GoogleServices`select`[]🇯🇵 Japan Node`[]🚀 Node Selection`[]🇺🇲 US Node`[]🇭🇰 Hong Kong Node`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇸🇬 Singapore Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=Ⓜ️ Microsoft`select`[]🇭🇰 Hong Kong Node`[]🚀 Node Selection`[]🇺🇲 US Node`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇸🇬 Singapore Node`[]🇯🇵 Japan Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🍎 Apple`select`[]🇭🇰 Hong Kong Node`[]🚀 Node Selection`[]🇺🇲 US Node`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇸🇬 Singapore Node`[]🇯🇵 Japan Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🎮 Gaming Platform`select`[]🇯🇵 Japan Node`[]🚀 Node Selection`[]🇺🇲 US Node`[]🇭🇰 Hong Kong Node`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇸🇬 Singapore Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🎮 Steam`select`[]🇯🇵 Japan Node`[]🚀 Node Selection`[]🇺🇲 US Node`[]🇭🇰 Hong Kong Node`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇸🇬 Singapore Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
;custom_proxy_group=🎶 NetEaseMusic`select`[]DIRECT`[]🚀 Node Selection`[]♻️ Automatic Selection`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 Direct Connection`select`[]DIRECT`[]🚀 Node Selection`[]♻️ Automatic Selection
;custom_proxy_group=🛑 Ad Block`select`[]REJECT`[]DIRECT
;custom_proxy_group=🍃 App Purification`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 Others`select`[]🇭🇰 Hong Kong Node`[]🚀 Node Selection`[]♻️ Automatic Selection`[]🇩🇪 German Node`[]🇨🇳 Taiwan Node`[]🇸🇬 Singapore Node`[]🇯🇵 Japan Node`[]🇺🇲 US Node`[]🇰🇷 Korea Node`[]🚀 Manual Switch`[]DIRECT
custom_proxy_group=🇭🇰 Hong Kong Node`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇩🇪 German Node`url-test`(German|Germany|德国|DE)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 Japan Node`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 US Node`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 Taiwan Node`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 Singapore Node`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 Korea Node`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎥 Netflix Node`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
custom_proxy_group=🌈 Usenet`select`[]DIRECT`.*
;Set the group logo bit

enable_rule_generator=true
overwrite_original_rules=true
udp=true
emoji=true
expand=false
classic=true
new_name=false

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
