[General]
# OpenClash remote YAML overwrite module (1 providers)
# Required variables: EN_SUB1

DOWNLOAD_FILE = url=https://cdn.jsdelivr.net/gh/x-bam/clash_config@main/cfg/yaml/Custom_Clash_1-Subs.yaml, path=/etc/openclash/config/Custom_Clash_1-Subs.yaml, force=true
CONFIG_FILE = /etc/openclash/config/Custom_Clash_1-Subs.yaml
SUB_INFO_URL = $EN_SUB1
RESTART = true

[Overwrite]
ruby_map_edit "$CONFIG_FILE" "['proxy-providers']" "provider1" "['url']" "$EN_SUB1"
